### ISSUE TITLE
Can't create two items with of different templates but with the same field

### ISSUE THREAD

**Issue by vadimzozulya** [sergeyshushlyapin/Sitecore.FakeDb#132]
The following code throws an exception:
```
var fieldId = ID.NewID;
var template1Id = ID.NewID;
var template2Id = ID.NewID;
using (new Db
         {
           new DbItem("parent", ID.NewID, template1Id) { new DbField("field", fieldId) { Value = "2" } },
           new DbItem("child", ID.NewID, template2Id) { new DbField("filed", fieldId) { Value = "1" } }
         })
{
}
```
Exception
```
System.InvalidOperationException: System.InvalidOperationException : An item with the same id has already been added ('{7E458F72-6FDD-4D41-A540-2E5CA7A15ADA}', '/sitecore/templates/child/Data/filed').
   at Sitecore.FakeDb.Data.Engines.DataStorage.AssertDoesNotExists(DbItem item)
   at Sitecore.FakeDb.Data.Engines.DataStorage.AddFakeItem(DbItem item)
   at Sitecore.FakeDb.Data.Engines.DataStorage.AddFakeItem(DbItem item)
   at Sitecore.FakeDb.Data.Engines.DataStorage.AddFakeItem(DbItem item)
   at Sitecore.FakeDb.Pipelines.AddDbItem.CreateTemplate.Process(AddDbItemArgs args)
   at (Object , Object[] )
   at Sitecore.Pipelines.PipelineMethod.Invoke(Object[] parameters)
   at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args)
   at Sitecore.Pipelines.CorePipeline.Run(String pipelineName, PipelineArgs args, String pipelineDomain, Boolean failIfNotExists)
   at Sitecore.FakeDb.Data.Engines.DataStorage.AddFakeItem(DbItem item)
   at Sitecore.FakeDb.Db.Add(DbItem item)
```

**Comment by pveller** [comment]
You need to create your fake template items if you want to give them your own IDs. Otherwise FakeDb will generate one for you. We can fix the error and let it silently do what it refuses to do now, but it will probably hide the fact that you are not getting what you wanted. I will send a code sample later today to make it more clear.

**Comment by sergeyshushlyapin** [comment]
Hi all!

Please let me explain what's going on here. @vadimzozulya, you're creating two **different** templates specifying `template_1_Id` and `template_2_Id` explicitly:
```csharp
new DbItem("parent", ID.NewID, template1Id) { },
new DbItem("child", ID.NewID, template2Id) { }
```

When FakeDb adds a template, it also creates [template field items](https://github.com/sergeyshushlyapin/Sitecore.FakeDb/issues/80). Since you've specified the `fieldId` explicitly (`new DbField("field", __fieldId__)`), FakeDb tries to add the same **field item** for each of the two different templates which is impossible. The exception is expected here.

There are couple of options how you can rewrite the test.

1. Do not specify the template id (the same auto-generated template will be reused for both items because they have similar set of fields):
  ```
  db.Add(new DbItem("parent") { new DbField("field", fieldId) { Value = "2" } });
  db.Add(new DbItem("child") { new DbField("filed", fieldId) { Value = "1" } });
  ```

2. Do not share the same field id between different templates. There will be two different templates with *similar* (but not *same*) fields:
  ```
  db.Add(new DbItem("parent", ID.NewID, template1Id) { new DbField("field") { Value = "2" } });
  db.Add(new DbItem("child", ID.NewID, template2Id) { new DbField("filed") { Value = "1" } });
  ```

3. Omit as much irrelevant data as possible:
  ```csharp
  db.Add(new DbItem("parent") { { fieldId, "2" } });
  db.Add(new DbItem("child") { { fieldId, "1" } });
  ```

**Comment by vadimzozulya** [comment]
Hi @sergeyshushlyapin, our code under tests should work only with the specific templates. We have two templates with common base template. Base template has a field with specific id which is read by our code. So we can't omit any of those ids.

@pveller it would be great to see code sample.

**Comment by pveller** [comment]
Take a look at these samples: 
* https://github.com/sergeyshushlyapin/Sitecore.FakeDb/wiki/Creating-an-Item-Based-on-a-Template
* https://github.com/sergeyshushlyapin/Sitecore.FakeDb/wiki/Creating-a-Hierarchy-of-Templates 

And remember that when you base your fake item on a template that you supply, you need to declare fields on the template. Basically, a fake item without a template will receive an auto-generated template auto-populated with field definition items based on what you declared on the item. If you provide a template item, FakeDb will use its definition to construct the set of item's fields. Fields that you declare on the item directly but don't declare on its template will be ignored. I hope it makes sense.

**Comment by vadimzozulya** [comment]
Thanks @pveller, adding hierarchy templates manually solve the problem.

Just for clarification previously we used "0.10.4" version (the project was not touched for years).
Code which is posted in the issue worked with that version.
