### ISSUE TITLE
dynamic serialization folder

### ISSUE THREAD

**Issue by dddkiran** [sergeyshushlyapin/Sitecore.FakeDb#135]
Hello!

We are using fakedb serialization to load test item, we want to use separate root folder (to extract items zip) for each feature. 

It is possible by adding new szfolders in "FakeDB.Serialization.config" which is not very clean.

Could you please expose constructor in DsDbItem class or Could you please provide any other possibility to directly pass the directory we want to use.

Thank you.

Namaste 
Kiran

**Comment by sergeyshushlyapin** [comment]
@dddkiran thanks for posting this wish.

Is there anything that prevents you from grouping your tests under the same *serialization folder*?
```csharp
    [Fact]
    public void Feature1001Test()
    {
      using (var db = new Sitecore.FakeDb.Db
        {
          new DsDbItem("/sitecore/content/feature_1001", true)
        })
      {
        // test feature 1
      }
    }

    public void Feature1002Test()
    {
      using (var db = new Sitecore.FakeDb.Db
        {
          new DsDbItem("/sitecore/content/feature_1002", true)
        })
      {
        // test feature 1002
      }
    }
```

//cc: @hermanussen

**Comment by hermanussen** [comment]
I'm sorry, but I'm not sure what the problem is.

You can add entries to the szfolders element in the configuration.

Then use one of the DsDbItem constructors that allows you to specify the name of the szfolder.

[Check the constructors on lines 32-40 here.](https://github.com/sergeyshushlyapin/Sitecore.FakeDb/blob/master/src/Sitecore.FakeDb.Serialization/DsDbItem.cs)

I implemented it this way, so you can define multiple places to store your serialized items and you don't have to reference the full path.

By default, the implementation will look for a szfolder entry which has a name that corresponds with the context database's name, and then defaulting to "master". But it is by no means a requirement to have szfolder entries that correspond with database names.

**Comment by sergeyshushlyapin** [comment]
@dddkiran is there anything we can help you with?

**Comment by sergeyshushlyapin** [comment]
Closed due to inactivity. Feel free to reopen if needed.
