### ISSUE TITLE
Adding item in non-en language doesn't work.

### ISSUE THREAD

**Issue by mikeedwards83** [sergeyshushlyapin/Sitecore.FakeDb#138]
If you add a child item using the following code:

    var parent = Database.GetItem("/parent",Language.Parse("fr-FR"));
    var child  = parent.Add("newitem", new TemplateID(templateId));

The child item is created in the EN language and not fr-FR, this I think is different to SC default behaviour.

**Comment by pveller** [comment]
Hey Mike. I am sure you know how it works behind the scenes right? I once blogged about it - http://jockstothecore.com/items-fields-versions-languages/. Languages and versions are not on the item. They are on the field values. When Sitecore creates a new empty item it just knows to insert a value into one field that is known to be versioned - `Created`. You basically can't have an item in a given language. You can only have its `Versioned` and `Unversioned` fields in a given language. 

Can you maybe post more of your test scenario so I could see how you are using the newly created item?

**Comment by mikeedwards83** [comment]
This is my original test using the Sitecore API directly:
https://github.com/mikeedwards83/Glass.Mapper/blob/develop/Tests/Integration%20Tests/Sitecore/Glass.Mapper.Sc.Integration/SitecoreServiceFixture.cs#L1601

and then converted to FakeDB:

https://github.com/mikeedwards83/Glass.Mapper/blob/features/fakeDb/Tests/Unit%20Tests/Glass.Mapper.Sc.FakeDb/SitecoreServiceFixture.cs#L2111

So I am not sure of the specifics inside of Sitecore but the standard Sitecore code will create and return a blank item.

**Comment by mikeedwards83** [comment]
Those tests are probably confusing because they are Glass specific so let me know if you want me to talk through any of it.

**Comment by pveller** [comment]
Alright. And last question from me. Would you please describe the difference in observed behavior between the two examples? It sounds like the crux of the problem is int:

```
Assert.AreEqual(lang, child.Language);
```

correct? You get the right language on the version with the stock Sitecore database and you get `en` with FakeDb, right?

**Comment by mikeedwards83** [comment]
This image hopefully shows the difference:

![](http://www.glass.lu/-/media/images/other/fakedb.ashx)

**Comment by pveller** [comment]
All clear. Let me look at it. I will be back

**Comment by pveller** [comment]
Reproduced it. You are correct. Sitecore does create the item with the language of the parent. Here's how I quickly tested:

```powershell
PS master:\>$item = [Sitecore.Context]::Database.GetItem("/sitecore/content", [Sitecore.Globalization.Language]::Parse("fr-FR"))
PS master:\>$item
 
Name                             Children Language Version Id                                     TemplateName
----                             -------- -------- ------- --                                     ------------
content                          True     fr-FR    1       {0DE95AE4-41AB-4D01-9EB0-67441B7C2450} Main section
 
 
PS master:\>$item.Add("test", $item.Template)
 
Name                             Children Language Version Id                                     TemplateName
----                             -------- -------- ------- --                                     ------------
test                             False    fr-FR    1       {A5D5C7AF-3C43-4ED0-BA13-A38D72AE4CA6} Main section
 
 
PS master:\>[Sitecore.Globalization.Language]::Current
 
 
CultureInfo : en
Origin      : Sitecore.Globalization.LanguageOrigin
Name        : en
Title       : English
Cacheable   : True
Immutable   : True
```

FakeDb would do the right thing if you use the `LanguageSwitcher` but you shouldn't have to. FakeDb's command implementation doesn't really create an item as you can imagine. We create a *fake* item. We then virtualize it "on read" but at that time the language of the parent is of course not known. 

I don't have a solution yet but at least I know what's going on.

**Comment by pveller** [comment]
Interestingly enough, if you re-read the item you won't have it in the `fr-FR` and neither will the item have a version. And its language will be back to `en`:

```powershell
PS master:\>$test = [Sitecore.Context]::Database.GetItem("/sitecore/content/test")
PS master:\>$test.Versions
 
Count
-----
    0
 
 
PS master:\>$test.Language
 
 
CultureInfo : en
Origin      : Sitecore.Globalization.LanguageOrigin
Name        : en
Title       : English
Cacheable   : True
Immutable   : True
```

I really wonder if we can do anything about it.

**Comment by pveller** [comment]
I think I found it. The way FakeDb adds an item is via its own "micro-pipeline" - `addDbItem`. In there we create a version via:

```
args.DbItem.AddVersion(Language.Current.Name);
```

This is why you are getting `en` and why `LanguageSwitcher` helps. The right way to fix it would be to send the language through the pipeline so that we could control and use the parent's language (or rather the destination item's language) for `AddFromTemplateCommand`. 

Looking into it now.

**Comment by sergeyshushlyapin** [comment]
@mikeedwards83, @pveller thanks for looking into this issue! You've discovered a lot in this few hours :)

Couple of month ago I was doing some POC (in the [no-commands](https://github.com/sergeyshushlyapin/Sitecore.FakeDb/commits/no-commands) branch) moving the logic from Data Commands to the [FakeDataProvider](https://github.com/sergeyshushlyapin/Sitecore.FakeDb/blob/no-commands/src/Sitecore.FakeDb/Data/DataProviders/FakeDataProvider.cs). I don't recall why exactly I decided to try this out, but I was surprised that the code became simpler! IIRC, mainly because the provider operates with either primitive types or with `ItemDefinition` (which is a simple DTO).

I just rebased it to the latest master, the issue is not reproduced! I don't know exactly which part has fixed it but I'd like to figure that out.

@pveller, thank you for the quick fix! Please give me some to investigate if there is an easier way to solve the bug.

**Comment by pveller** [comment]
@sergeyshushlyapin I think I know why. This whole ordeal with item manipulations goes like this:

```
Item -> 
    ItemManager ->
        ItemProvider ->
            Database DataEngine ->
                Database Commands ->
                    Nexus.DataApi Commands -> 
                        Data Provider ->
                            Chain of Data Providers
```

Sometimes the chain stops in the `Nexus DataApi` like it does, for example, for `AddFromTemplateCommand` and sometimes it goes straight to the DataProvider and that's why we always had the `FakeDataProvider`.

Anyway. Your original design intercepted on the database command level. Once you let it go all the way through into the `DataProvider` you let the logic in `Nexus.DataApi` do its thing and in this case it is actually helping the issue @mikeedwards83 brought up. That logic is in there somewhere I believe. Hard to the read the code that went through the control flow obfuscation but one can still pick up pieces :)

**Comment by bhatiarahul10** [comment]
Hi pveller

I am trying to create a multi lingual item however I am not following the way its specified in the wiki.
Below is the code that I have written
I create a DB template with fields
var itemTemplate = new DbTemplate("Base Template", tempSitecoreId);
foreach (var f in _fields)
{
    itemTemplate.Add(new DbField(f.Key, ID.NewID));
}
Then from this template I create a new DBItem and finally create a version for the item in language.
Then on the item I set the fields
Item item = null; ;
if (!string.IsNullOrEmpty(languages))
{
	using (new LanguageSwitcher(languages))
	{
	var tempSitecoreId = _sitecoreTemplateID ?? ID.NewID;
	CreateTemplate(tempSitecoreId);
	var dbItem = new DbItem(_name, ID.NewID, tempSitecoreId);
	dbItem.AddVersion(languages);
	_siteCoreDb.Add(dbItem);
	item = _siteCoreDb.Database.GetItem(dbItem.ID, Language.Parse(languages ?? "en"));
	SetFields(item);
}
}
return item;	

Setting Fields
item.Editing.BeginEdit()
item.Fields["FieldName"].Value="Git"

This all works fine until the language is English, however when using some other language say "ja" the values get set in En language item leading to a failing test case which needs the fields to be set upon Japanese item.

Please suggest. Also I need to make the item in this way only as I am passing all the parameters at runtime from the test itself

**Comment by bhatiarahul10** [comment]
Here's the link to my git repo . https://github.com/bhatiarahul10/Sitecore
I have pushed in two sample unit tests
The first one with Japanese language fails as the output items are empty. However the second one passes. The tests are included in Sitecoregit.cs file.
