### ISSUE TITLE
Fake Link Database does not work via the Configuration Factory.

### ISSUE THREAD

**Issue by mikeedwards83** [sergeyshushlyapin/Sitecore.FakeDb#141]
Using the following code works:

               var behavior = Substitute.For<Sitecore.Links.LinkDatabase>();

                behavior.GetReferrers(target).Returns(new[]
                {
                    new Sitecore.Links.ItemLink(source, fieldId, target, target.Paths.FullPath),
                });

                using (new Sitecore.FakeDb.Links.LinkDatabaseSwitcher(behavior))
                {
                       var results = Sitecore.Globals.LinkDatabase.GetReferrers(item);
                }

However this code doesn't work:

               var behavior = Substitute.For<Sitecore.Links.LinkDatabase>();

                behavior.GetReferrers(target).Returns(new[]
                {
                    new Sitecore.Links.ItemLink(source, fieldId, target, target.Paths.FullPath),
                });

                using (new Sitecore.FakeDb.Links.LinkDatabaseSwitcher(behavior))
                {
                       var linkDb = global::Sitecore.Configuration.Factory.GetLinkDatabase();

                       var results = linkDb.GetReferrers(item);
                }

Is this intended that the Link Databases via the config factory is different.

Interestingly global::Sitecore.Configuration.Factory.GetLinkDatabase() == itecore.Globals.LinkDatabase is false.

I think I will just convert to using the global in my code.

**Comment by sergeyshushlyapin** [comment]
The difference is the following. `Globals` uses Configuration Factory to create an instance of the Link Database and *stores* it in a private static field. The `Globals.LinkDatabase` property returns the same instance all the time.

In the same time, the Factory resolves the Link Database from the [config](https://github.com/sergeyshushlyapin/Sitecore.FakeDb/blob/master/src/Sitecore.FakeDb/Sitecore.config#L70):
```xml
    <!-- LINK DATABASE -->
    <LinkDatabase type="Sitecore.FakeDb.Links.FakeLinkDatabase, Sitecore.FakeDb" />
```

Since the registration is not marked as a singleton (unlike [Database](https://github.com/sergeyshushlyapin/Sitecore.FakeDb/blob/master/src/Sitecore.FakeDb/Sitecore.config#L132)), a new *unconfigured* instance of the Link Database returned.

**Comment by sergeyshushlyapin** [comment]
The Link Database is not a singleton in the production Sitecore version as well. There is the registration from 8.2 config:
```xml
  <!-- LINK DATABASE -->
  <LinkDatabase type="Sitecore.Data.$(database).$(database)LinkDatabase, Sitecore.Kernel">
    <param connectionStringName="core" />
  </LinkDatabase>
```

Despite marking the Link Database as a singleton might solve the problem, that is a good way to go since dealing with singletons in unit tests is [problematic](http://stackoverflow.com/questions/2085953/unit-testing-with-singletons). Is there any option to inject the `LinkDatabase` *abstract* class into SUT so that neither `Globals` nor `Factory` is used?

**Comment by sergeyshushlyapin** [comment]
@mikeedwards83, as I mentioned above, that is not a FakeDb issue so I'll close it. If there are any other questions regarding this, feel free to reopen.
