### ISSUE TITLE
Disposing Language Switcher fails if current Switcher<> is empty

### ISSUE THREAD

**Issue by sergeyshushlyapin** [sergeyshushlyapin/Sitecore.FakeDb#166]
Related to #161.

In some _rare_ cases the `Sitecore.Common.Switcher<DbLanguages>.CurrentValue` returns null. This leads to exception when disposing a `Db` instace:

```
System.InvalidOperationException: Stack is null or empty.
   at Sitecore.Common.Switcher`2.Exit()
   at Sitecore.Common.Switcher`2.Dispose()
   at Sitecore.FakeDb.Db.Dispose(Boolean disposing) 
```

**Comment by sergeyshushlyapin** [comment]
Fixed in [v1.5.0](https://www.nuget.org/packages/Sitecore.FakeDb/).

**Comment by Manoharan13** [comment]
Using Sitecore.FakeDb Version 1.7.4.0. In some cases, getting the below error.
### System.InvalidOperationException: Stack is null or empty.
   at Sitecore.Common.Switcher`2.Exit()
   at Sitecore.Common.Switcher`2.Dispose()
Below is code. Not sure what went wrong. Please help.
### 
try {
                using (new Sitecore.Security.Accounts.UserSwitcher(@"extranet\demo", true))
                {
                    HttpContext.Current = MockHelpers.FakeHttpContext(); //Mocking the session                   
                    var objRes = new PolicyLogic().GetDetailsbypolicynumber("123456789");
                    Assert.IsTrue(objRes != null && objRes.Documents.Count > 0);
                }
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }
Thanks

**Comment by sshushliapin** [comment]
Hi @Manoharan13, just refactored your test to get [minimal verifiable sample](https://stackoverflow.com/help/mcve) (there are no `MockHelpers` and `PolicyLogic` classes on my side):

    using (new Sitecore.Security.Accounts.UserSwitcher(@"extranet\demo", true))
    {
        var request = new HttpRequest(string.Empty, "http://mysite", string.Empty);
        var response = new HttpResponse(new StringWriter());
        HttpContext.Current = new HttpContext(request, response);
    }

The problem is in _resetting_ current HTTP context and unfortunately FakeDb has nothing to do here. 

Please take a look on the `Switcher<,>` class. It keeps 'switched contexts' in the `Sitecore.Context.Items` property which refers to `HttpContext.Current` (see `ItemsContext` class). Resetting the current http context kills the stored switchers and that's why you receive this error.

The recommendation is to avoid http context resetting and inject dependencies into your code as needed instead of relying on the current context.
