### ISSUE TITLE
Is Sitecore.Publishing.Publisher supported?

### ISSUE THREAD

**Issue by ethan-agencyQ** [sergeyshushlyapin/Sitecore.FakeDb#178]
Hi, first of all, thanks very much for making testing easy in Sitecore, I enjoy using FakeDb very much.

So here is my story. I have to test a function that creates and publishes a Sitecore item. The creating part is a breeze, but when it moves to publishing, it throws a null reference error at the Publisher.HandleFailedPublish function, this is not very useful and I feel it's hiding the true error. 

After some digging and debugging, I got the actual error "_Could not find configuration node: publishManager_" thrown by Publisher.PublishWithResult. Well, the node is indeed missing in the test project. And that leads me here and ask this question, I wonder if I can test publish with FakeDB.

**Comment by sergeyshushlyapin** [comment]
@ethan-agencyQ, there are few possible solutions to this:

1. You may add the missing node to your tests 'App.config' file. Depending on your needs, you may implement and register  a _stub_ or _fake_ `PublishProvider`
2. FakeDb might do the same so that it's available OOTB
3. In case of Sitecore 8.2, you may simply mock the `Publisher` since all it's methods are `virtual`

I'd, of course, vote for option 2 but unfortunately this scheme [does not for 8.2+ versions](https://github.com/sergeyshushlyapin/Sitecore.FakeDb/pull/154#issue-194631353) anymore. Even if I implement some kind of a `SwitchingPublishingProvider` for 8.0-8.1 versions, I'll _probably_ have to [obsolete it _immediately_ for Sitecore 8.2](https://github.com/sergeyshushlyapin/Sitecore.FakeDb/issues/175)...

So, if possible, I'd recommend you to go with option 3. If not - option 1 as a temporary solution until you upgrade to Sc 8.2.

**Comment by ethan-agencyQ** [comment]
Thanks, GitHub not giving me notifications on this thread for some reason, sorry that my response is late. I really like solution 3, but my current code based uses the publisher in a static extension method, which is not really easy to mock... I will need to restructure the code so that I can supply a mocked Publisher.

Thanks!
