### ISSUE TITLE
NameValueList field

### ISSUE THREAD

**Issue by ptcdrummer** [sergeyshushlyapin/Sitecore.FakeDb#190]
Hi Sergey,
I'm trying to fake a custom item for testing, and the item has a NameValueList field. I'm trying to find a way to define this in my faked item. Do you have any suggestions?

**Comment by sergeyshushlyapin** [comment]
I suppose [this answer](https://github.com/sergeyshushlyapin/Sitecore.FakeDb/issues/186#issuecomment-333295865) is valid in your case as well. The only difference is that you should use `&` instead of `|`:

![image](https://user-images.githubusercontent.com/4719165/32246864-0d5d297c-be89-11e7-80f8-6616cde4e605.png)

Raw value that you should put into a `DbItem` field:

![image](https://user-images.githubusercontent.com/4719165/32246818-ef0f0580-be88-11e7-919c-d0f5e9839396.png)

**Comment by ptcdrummer** [comment]
Thanks! I had actually already done it the way you suggest, but was hoping for a way to use a field with the ability to add nvp entries using the same {"name", "value"} notation used when adding DBItems. No worries, though. I can still use the name1=value1&... method.
