### ISSUE TITLE
Glass Mapper

### ISSUE THREAD

**Issue by vtml** [sergeyshushlyapin/Sitecore.FakeDb#24]
Hi,

I am using Glass Mapper, and would like to map Rich Text editor string fields by using
item.GlassCast<Page>()

I am getting a mapping error because obviously there is no proper SitecoreContext.
Any ideas on how to get around this by any chance ?

I have tried following the steps here but it did not work.
https://github.com/Glass-lu/Glass.Sitecore.Mapper/issues/38

**Comment by sergeyshushlyapin** [comment]
The recent post [Life Through a Lens – Glass Tip – Casting Items to Objects in Glass Mapper](http://cardinalcore.co.uk/2015/01/05/life-through-a-lens-glass-tip-casting-items-to-objects-in-glass-mapper/) from @cardinal252 inspired me to review the discussion and simplify the code samples.

It appeared that `FakeDb` is not really needed here. In order to configure the `ISitecoreContext` mock **any** item can be used. It can be created either via FakeDb or Glass Utilities or even using the constructor of the Sitecore Item class.

I decided to go with the `Glass.Mapper.Sc.Utilities.CreateFakeItem()` helper method because it was the simplest solution (IMO):

```csharp
[Fact]
public void HowToMockGlassCastInUnitTests()
{
  // arrange - configure fake data and mocks
  var item = Glass.Mapper.Sc.Utilities.CreateFakeItem(new Dictionary<Guid, string>());
  var myObject = Substitute.For<IMyObject>();

  var sitecoreService = Substitute.For<Glass.Mapper.Sc.ISitecoreService>();
  sitecoreService.Cast<IMyObject>(item).Returns(myObject);

  // act - test your business logic here
  var actualResult = sitecoreService.Cast<IMyObject>(item);

  // assert
  Xunit.Assert.Same(myObject, actualResult);
}
```
