### ISSUE TITLE
Item Versions

### ISSUE THREAD

**Issue by mikeedwards83** [sergeyshushlyapin/Sitecore.FakeDb#28]
How do I tell fake db explicitly not to create a version in a specific language?

For example the following test:

```
        using (Sitecore.FakeDb.Db db = new Sitecore.FakeDb.Db
        {            
            new Sitecore.FakeDb.DbItem(itemName2, itemId2)
            {
                new DbField(FieldName)
                {
                    {"en",1,"faea"}
                }
            }
        })
        {

            var language = LanguageManager.GetLanguage("af-ZA");
            var target = database.GetItem("/sitecore/content/{0}".Formatted(itemName2), language);

            Assert.AreEqual(0, target.Versions.Count);
       }
```

Will fail because FakeDb always returns an entry n the Versions list for the requested language. This is different from Sitecore's default behaviour which is to return an empty Versions list.

**Comment by vtml** [comment]
Having a a Version issue here a well.
Sitecore's default behaviour to determine whether a language version exists is something along the lines of

Item item3 = ItemManager.GetItem(itemPath, currentLanguage, Version.Latest, database);

if (item3 != null && item3.Versions.Count > 0)
{
 //Versions.Count > 0 was added because sitecore always returns an item
}

In Sitecore.FakeDb, if a language does not exist, item3 will be null. If the language item exists, item3 is not null, however item3.Versions.Count is 0.

**Comment by sergeyshushlyapin** [comment]
@vtml I run the same code in FakeDb and my integration tests (default Sitecore). It behaves the same. Am I missing something?

```csharp
using (var db = new Db { new DbItem("home") })
{
  // default lang, item is not null, versions count is 1
  db.GetItem("/sitecore/content/home", "en").Versions.Count.Should().Be(1);
  // custom lang, item is not null, versions count is 0
  db.GetItem("/sitecore/content/home", "uk-UA").Versions.Count.Should().Be(0);
}
```

Integration tests:
```csharp
var database = Sitecore.Data.Database.GetDatabase("master");
// default lang, item is not null, versions count is 1
database.GetItem("/sitecore/content/home", Language.Parse("en")).Versions.Count.Should().Be(1);
// custom lang, item is not null, versions count is 0
database.GetItem("/sitecore/content/home", Language.Parse("uk-UA")).Versions.Count.Should().Be(0);
```

**Comment by vtml** [comment]
I just worked out what it is. The LanguageManager inside Sitecore.FakeDb has one language ("en") only. If you do LanguageManager.GetLanguages() it will only show one, hence ItemManager.GetItem() will not resolve the correct version when I am trying to query an Item with the language which is not "en".

I think I will just need to stub out my method more to cater for this so that I can pass a list of Languages in.

**Comment by sergeyshushlyapin** [comment]
> *hence ItemManager.GetItem() will not resolve the correct version when I am trying to query an Item with the language which is not "en".*

Could you please provide a failing test for this? If smth is wrong I want it to be fixed. Thanks.

**Comment by vtml** [comment]
Disregard.
It's actually a confusion with my deserialised item.
