### ISSUE TITLE
DbItem constructor with children params

### ISSUE THREAD

**Issue by AlenPelin** [sergeyshushlyapin/Sitecore.FakeDb#45]
It would be really handy if DbItem has XElement like constructor:

```
var item = new DbItem("/sitecore/content/Home", 
  new DbItem("child1", 
    new DbItem("grandchild1")));
```

**Comment by pveller** [comment]
There are a few constructors that I was always missing but this was not on my list. We short-circuited the `IEnumerable.Add()` so you can always do:

```csharp
var item = new DbItem("/sitecore/content/Home")
{
  new DbItem("child1") { new DbItem("grandchild1") }
}
```
You can't (unfortunately) mix property initializer with collection initializers so when you need both you have to reset to calling `.Add()` explicitly. For the simple instantiation though I prefer the `{}` syntax.

**Comment by AlenPelin** [comment]
This wish went live 20 seconds before I had another look at documentation :disappointed:, but anyway I think it should be possible to implement that 

```c#
public DbItem(string name, ID id, ID templateId, params DbObject[] children) : this(name, id, templateId)
{
  foreach(var child in children)
  {
    if(child is DbItem)
    { 
      ...
    } 
    else if(child is DbField) 
    {
      ...
    }
  }
}
```

**Comment by sergeyshushlyapin** [comment]
I assume the `Db` class should get the similar constructor. The model you suggest is a bit more compact comparing to the existing one:

```csharp
using (Sitecore.FakeDb.Db db = new Sitecore.FakeDb.Db(
  new Sitecore.FakeDb.DbItem(
    "Articles",
    new Sitecore.FakeDb.DbItem("Getting Started"),
    new Sitecore.FakeDb.DbItem("Troubleshooting"))))
```

```csharp
using (Sitecore.FakeDb.Db db = new Sitecore.FakeDb.Db
  {
    new Sitecore.FakeDb.DbItem("Articles")
      {
        new Sitecore.FakeDb.DbItem("Getting Started"),
        new Sitecore.FakeDb.DbItem("Troubleshooting")
      }
  })
```

Technically that is a trivial change; it won't break the existing functionality.  

The question is whether this code still as easy to read as before. I'm a bit confused by the four closing brackets `))))` in the last line:

```csharp
    new Sitecore.FakeDb.DbItem("Troubleshooting"))))
```

That might be a question of code style preferences, so if somebody likes it I don't see a reason why it shouldn't be implemented.

**Comment by sergeyshushlyapin** [comment]
Hi all,

A friendly team reported a pretty interesting issue. The following code fails:
```csharp
// arrange
var id = Guid.NewGuid();
      
// act
using (var db = new Db { new DbItem("name", id) })
{
  // assert
  db.GetItem(id.ToString()).Should().NotBeNull(); // the item is null because the id has not been set
}
```

The reason for this is that I expect the following constructor to run:
```csharp
public DbItem(string name, ID id, params object[] children)
```

.. but in fact the next one is called:
```csharp
public DbItem(string name, params object[] children)
```

This leads to the situation when my item id (and template id as well) is getting lost.. **Silently**. *Guids* are not allowed to be used in the `DbItem` constructors. In the earlier versions one would get a compilation error and had to cast the `Guid` identifier to a Sitecore `ID`, but now it neither fail nor work correctly which is very confusing.

Of course it would be more correct to use `params DbItem[]` instead of the `params object[]` but there is another issue with that approach. In this case AutoFixture cannot create a `DbItem` instance **without advanced customizations**:

```csharp
var fixture = new Fixture();
var item = fixture.Create<DbItem>();

// throws:
// Ploeh.AutoFixture.ObjectCreationException: AutoFixture was unable to create an instance of type
// Ploeh.AutoFixture.Kernel.FiniteSequenceRequest because the traversed object graph contains a
// circular reference.
```

I consider the both described scenarios more important than the suggested feature and I tend to revert it back (unfortunately it has been published to public, but since it was not so long time ago, I think it's not too late).

Any thoughts or objections? Thanks.

**Comment by sergeyshushlyapin** [comment]
// cc: @alexsokolov

**Comment by pveller** [comment]
I agree. The constructor parameter is more of a convenience. The other two are more of a necessity.

**Comment by sergeyshushlyapin** [comment]
Reverted and pushed as part of 0.28.1
