### ISSUE TITLE
Fake test for Events

### ISSUE THREAD

**Issue by a3codeDA** [sergeyshushlyapin/Sitecore.FakeDb#87]
Is it possible to make some fake tests for events like item added, item created (ItemCreatedEvent)  etc ?

**Comment by sergeyshushlyapin** [comment]
Could you please elaborate what kind of test you're talking about? Would you like to test that SUT *triggers* some event with specific args? Or that the event handler itself can be unit tested.

**Comment by sergeyshushlyapin** [comment]
So, please confirm that I understand the your request correctly. You'd like to:
1. Call a SUT which, for instance, creates an item
2. The `item:created` event should be triggered and some *handler* should be called
3. Check that the handler has done the good job

**Comment by a3codeDA** [comment]
Sorry for late replay, yes your step it exactly that I have asked.

**Comment by sergeyshushlyapin** [comment]
You need to check that two classes (one that *creates* an item and one that *handles* the `item:created` event) and the handler registration in the config file works correctly. IMO that is a good scenario for an integration test.
But, to be honest, I never tried to configure events in unit tests, so it might worth to research it.

**Comment by a3codeDA** [comment]
I tried add handler description to app.config at unit test but it doesn't work...
How I should create a fake trigger for test ?
```xml
<sitecore database="Fake">
    <!-- events -->
    <events>
      <event name="item:created">
        <handler type="MyLib.Validator, MyLib" method="OnItemCreated" />
      </event>
    </events>
.....
</sitecore>
```

**Comment by sergeyshushlyapin** [comment]
In order to make it working the `Sitecore.Events.Event.Initialize();` method needs to be called. The best place is the static constructor of the `Sitecore.FakeDb.Configuration.ConfigReader` class which is some kind of an *entry point* into the FakeDb life-cycle.

I'm still in doubts that it should be enabled by default. The handler registration in config can significantly break the tests isolation. Imagine what happens if the handler get broken. It may fail numerous other tests only because they are *subscribed* to the same `item:created` event.

**Comment by sergeyshushlyapin** [comment]
From the other side, initializing the `Event` class without adding any registrations to the default `App.config` file will not make the FakeDb less stable. So as soon as you aware about the potential risks, and it solves your problem, I'm OK to add that :)

**Comment by sergeyshushlyapin** [comment]
I prototyped a bit around the problem and have to admit that unit(?) testing of the main *actor* (Creator) + *config registration* + *advanced* behavior (Validator) in a single test might be acceptable as soon as you're able to [keep it stupid simple](https://en.wikipedia.org/wiki/KISS_principle). Rob Conery in his [Pragmatic Behavior-driven Design with .NET](http://www.pluralsight.com/courses/pragmatic-bdd-dotnet) course shows something similar focusing on the overall system behavior rather than testing small isolated pieces.

```csharp
using System;
using Ploeh.AutoFixture;
using Ploeh.AutoFixture.Xunit2;
using Sitecore;
using Sitecore.Data;
using Sitecore.Data.Events;
using Sitecore.Data.Items;
using Sitecore.Data.Managers;
using Sitecore.Events;
using Sitecore.FakeDb.AutoFixture;
using Xunit;

namespace EventsPoc
{
  public class CreatorTest
  {
    // All the argument validation tests are omitted.

    [Theory, DefaultAutoData]
    public void SutCreatesNewGoodItem(Creator sut)
    {
      sut.Create("good item");
      Assert.Single(sut.Root.Children);
    }

    [Theory, DefaultAutoData]
    public void SutDoesNotCreateBadItem(Creator sut)
    {
      sut.Create("bad item");
      Assert.Empty(sut.Root.Children);
    }

    private class DefaultAutoDataAttribute : AutoDataAttribute
    {
      public DefaultAutoDataAttribute()
        : base(new Fixture()
                 .Customize(new AutoDbCustomization())
                 .Customize(new AutoContentCustomization()))
      {
      }
    }
  }

  public class Creator
  {
    public Creator(Item root)
    {
      Root = root;
    }

    public Item Root { get; private set; }

    public void Create(string itemName)
    {
      // No events fired if the following code is used (to be investigated):
      // Root.Add(itemName, new TemplateID(TemplateIDs.Folder));

      ItemManager.CreateItem(itemName, this.Root, new TemplateID(TemplateIDs.Folder));
    }
  }

  public class GoodItemValidator
  {
    public void OnItemCreating(object sender, EventArgs e)
    {
      var args = (SitecoreEventArgs)e;
      var itemCreatingArgs = (ItemCreatingEventArgs)args.Parameters[0];

      if (itemCreatingArgs.ItemName.Contains("bad"))
      {
        args.Result.Cancel = true;
      }
    }
  }
}
```

```xml
<!-- EVENTS -->
<events>
  <event name="item:creating">
    <handler type="EventsPoc.GoodItemValidator, EventsPoc" method="OnItemCreating" />
  </event>
</events>
```

Please note that the `ItemManager.CreateItem()` method successfully raises the events. No changes in FakeDb required.

**Comment by sergeyshushlyapin** [comment]
The list of the NuGet packages for the sample above:
```powershell
PM> Install-Package xunit
PM> Install-Package AutoFixture.Xunit2
PM> Install-Package Sitecore.FakeDb.AutoFixture
```
